 export const ImpersonateData={
  CommonUsers: [
    {
      "Id": 29294,
      "AdminUserGuid": "a67308b0-05bd-4d7a-8a34-70504aa81b35",
      "AdminUsername": "tschunk",
      "AdminFirstName": null,
      "AdminLastName": null,
      "UserFirstName": "IRIS Admin User",
      "UserLastName": "Anytime Fitness",
      "UserUsername": "IRISadminAFI_AFI",
      "UserClientName": "Anytime Fitness",
      "UserCompanyName": "TESTING - DO NOT PROCESS THIS ORDER!!!",
      "Url": "",
      "NumberOfHits": 1377,
      "UpdateDate": "/Date(1604978127000)/"
    },
    {
      "Id": 23576,
      "AdminUserGuid": "a67308b0-05bd-4d7a-8a34-70504aa81b35",
      "AdminUsername": "tschunk",
      "AdminFirstName": null,
      "AdminLastName": null,
      "UserFirstName": "IRIS",
      "UserLastName": "Admin",
      "UserUsername": "IRISadmin_mertg",
      "UserClientName": "Meritage Homes",
      "UserCompanyName": "IRIS Strategic Marketing Support",
      "Url": "",
      "NumberOfHits": 521,
      "UpdateDate": "/Date(1643628830000)/"
    },
    {
      "Id": 48892,
      "AdminUserGuid": "a67308b0-05bd-4d7a-8a34-70504aa81b35",
      "AdminUsername": "tschunk",
      "AdminFirstName": null,
      "AdminLastName": null,
      "UserFirstName": "Tim",
      "UserLastName": "Schunk",
      "UserUsername": "tschunk@irisnow.com_tpmco",
      "UserClientName": "The Personal Marketing Co. (TPMCO)",
      "UserCompanyName": "Ship To Me",
      "Url": "",
      "NumberOfHits": 353,
      "UpdateDate": "/Date(1618804086000)/"
    },
    {
      "Id": 6971,
      "AdminUserGuid": "a67308b0-05bd-4d7a-8a34-70504aa81b35",
      "AdminUsername": "tschunk",
      "AdminFirstName": null,
      "AdminLastName": null,
      "UserFirstName": "IRIS",
      "UserLastName": "ADMIN",
      "UserUsername": "plygemwindowsadmin_pgw",
      "UserClientName": "Ply Gem Windows VIP ",
      "UserCompanyName": "IRIS",
      "Url": "",
      "NumberOfHits": 332,
      "UpdateDate": "/Date(1629774794000)/"
    },
    {
      "Id": 27662,
      "AdminUserGuid": "a67308b0-05bd-4d7a-8a34-70504aa81b35",
      "AdminUsername": "tschunk",
      "AdminFirstName": null,
      "AdminLastName": null,
      "UserFirstName": "IRIS Superuser",
      "UserLastName": "Allegion",
      "UserUsername": "dbrennan@irisnow.com_alleg",
      "UserClientName": "Allegion",
      "UserCompanyName": "TEST ORDER/DO NOT FULFILL - IRIS Strategic Marketing Support",
      "Url": "",
      "NumberOfHits": 303,
      "UpdateDate": "/Date(1616741360000)/"
    },
    {
      "Id": 10612,
      "AdminUserGuid": "a67308b0-05bd-4d7a-8a34-70504aa81b35",
      "AdminUsername": "tschunk",
      "AdminFirstName": null,
      "AdminLastName": null,
      "UserFirstName": "Iris",
      "UserLastName": "Admin",
      "UserUsername": "irisadmin_andy",
      "UserClientName": "Andy's Restaurant",
      "UserCompanyName": "TEST COMPANY - DO NOT PROCESS",
      "Url": "",
      "NumberOfHits": 181,
      "UpdateDate": "/Date(1637309498000)/"
    },
    {
      "Id": 29640,
      "AdminUserGuid": "a67308b0-05bd-4d7a-8a34-70504aa81b35",
      "AdminUsername": "tschunk",
      "AdminFirstName": null,
      "AdminLastName": null,
      "UserFirstName": "IRIS Demo",
      "UserLastName": "VW",
      "UserUsername": "IRISdemoVW_VW",
      "UserClientName": "Volkswagen",
      "UserCompanyName": "Test Iris #1 Volkswagen of Lenexa",
      "Url": "",
      "NumberOfHits": 159,
      "UpdateDate": "/Date(1556685076000)/"
    },
    {
      "Id": 30582,
      "AdminUserGuid": "a67308b0-05bd-4d7a-8a34-70504aa81b35",
      "AdminUsername": "tschunk",
      "AdminFirstName": null,
      "AdminLastName": null,
      "UserFirstName": "IRIS Admin",
      "UserLastName": "Superuser",
      "UserUsername": "IRISsuper_pryor",
      "UserClientName": "Pryor Learning",
      "UserCompanyName": "IRIS",
      "Url": "",
      "NumberOfHits": 114,
      "UpdateDate": "/Date(1611635850000)/"
    },
    {
      "Id": 47278,
      "AdminUserGuid": "a67308b0-05bd-4d7a-8a34-70504aa81b35",
      "AdminUsername": "tschunk",
      "AdminFirstName": null,
      "AdminLastName": null,
      "UserFirstName": "IRIS",
      "UserLastName": "Admin",
      "UserUsername": "IRISadmin_tpmco",
      "UserClientName": "The Personal Marketing Co. (TPMCO)",
      "UserCompanyName": "TEST ORDER - DO NOT PROCESS",
      "Url": "",
      "NumberOfHits": 100,
      "UpdateDate": "/Date(1619069313000)/"
    },
    {
      "Id": 41589,
      "AdminUserGuid": "a67308b0-05bd-4d7a-8a34-70504aa81b35",
      "AdminUsername": "tschunk",
      "AdminFirstName": null,
      "AdminLastName": null,
      "UserFirstName": "IRIS",
      "UserLastName": "Admin",
      "UserUsername": "IrisAdmin_pront",
      "UserClientName": "Simonton ProNetwork",
      "UserCompanyName": "TEST COMPANY - DO NOT PROCESS",
      "Url": "",
      "NumberOfHits": 77,
      "UpdateDate": "/Date(1629774697000)/"
    }
  ],
  RecentUsers: [
    {
      "Id": 23576,
      "AdminUserGuid": "a67308b0-05bd-4d7a-8a34-70504aa81b35",
      "AdminUsername": "tschunk",
      "AdminFirstName": null,
      "AdminLastName": null,
      "UserFirstName": "IRIS",
      "UserLastName": "Admin",
      "UserUsername": "IRISadmin_mertg",
      "UserClientName": "Meritage Homes",
      "UserCompanyName": "IRIS Strategic Marketing Support",
      "Url": "",
      "NumberOfHits": 521,
      "UpdateDate": "/Date(1643628830000)/"
    },
    {
      "Id": 63850,
      "AdminUserGuid": "a67308b0-05bd-4d7a-8a34-70504aa81b35",
      "AdminUsername": "tschunk",
      "AdminFirstName": null,
      "AdminLastName": null,
      "UserFirstName": "VP",
      "UserLastName": "Admin",
      "UserUsername": "VPadmin_varco",
      "UserClientName": "Varco Pruden (VP)",
      "UserCompanyName": "Varco Pruden",
      "Url": "",
      "NumberOfHits": 1,
      "UpdateDate": "/Date(1642752534000)/"
    },
    {
      "Id": 63576,
      "AdminUserGuid": "a67308b0-05bd-4d7a-8a34-70504aa81b35",
      "AdminUsername": "tschunk",
      "AdminFirstName": null,
      "AdminLastName": null,
      "UserFirstName": "IRIS",
      "UserLastName": "Admin",
      "UserUsername": "IRISadmin_fuson",
      "UserClientName": "Fusion Marketing",
      "UserCompanyName": "Test Company ",
      "Url": "",
      "NumberOfHits": 2,
      "UpdateDate": "/Date(1641872351000)/"
    },
    {
      "Id": 25745,
      "AdminUserGuid": "a67308b0-05bd-4d7a-8a34-70504aa81b35",
      "AdminUsername": "tschunk",
      "AdminFirstName": null,
      "AdminLastName": null,
      "UserFirstName": "Audrey",
      "UserLastName": "Taylor",
      "UserUsername": "corpadmin_ma",
      "UserClientName": "Mastic",
      "UserCompanyName": "IRIS",
      "Url": "",
      "NumberOfHits": 41,
      "UpdateDate": "/Date(1638509612000)/"
    },
    {
      "Id": 62911,
      "AdminUserGuid": "a67308b0-05bd-4d7a-8a34-70504aa81b35",
      "AdminUsername": "tschunk",
      "AdminFirstName": null,
      "AdminLastName": null,
      "UserFirstName": "Kansas City",
      "UserLastName": "Admin User",
      "UserUsername": "KansasCityAdmin_citwd",
      "UserClientName": "City Wide - City Market",
      "UserCompanyName": "City Wide Franchise Company, Inc.",
      "Url": "",
      "NumberOfHits": 3,
      "UpdateDate": "/Date(1638435052000)/"
    },
    {
      "Id": 62907,
      "AdminUserGuid": "a67308b0-05bd-4d7a-8a34-70504aa81b35",
      "AdminUsername": "tschunk",
      "AdminFirstName": null,
      "AdminLastName": null,
      "UserFirstName": "IRIS",
      "UserLastName": "Admin",
      "UserUsername": "IrisAdmin_citwd",
      "UserClientName": "City Wide - City Market",
      "UserCompanyName": "TEST COMPANY - DO NOT PROCESS",
      "Url": "",
      "NumberOfHits": 2,
      "UpdateDate": "/Date(1638430551000)/"
    },
    {
      "Id": 10612,
      "AdminUserGuid": "a67308b0-05bd-4d7a-8a34-70504aa81b35",
      "AdminUsername": "tschunk",
      "AdminFirstName": null,
      "AdminLastName": null,
      "UserFirstName": "Iris",
      "UserLastName": "Admin",
      "UserUsername": "irisadmin_andy",
      "UserClientName": "Andy's Restaurant",
      "UserCompanyName": "TEST COMPANY - DO NOT PROCESS",
      "Url": "",
      "NumberOfHits": 181,
      "UpdateDate": "/Date(1637309498000)/"
    },
    {
      "Id": 62462,
      "AdminUserGuid": "a67308b0-05bd-4d7a-8a34-70504aa81b35",
      "AdminUsername": "tschunk",
      "AdminFirstName": null,
      "AdminLastName": null,
      "UserFirstName": "84LUMBER",
      "UserLastName": "RESCOOPACCT",
      "UserUsername": "84lumbercoop_alleg",
      "UserClientName": "Allegion MRC",
      "UserCompanyName": "Test",
      "Url": "",
      "NumberOfHits": 1,
      "UpdateDate": "/Date(1634527905000)/"
    },
    {
      "Id": 61415,
      "AdminUserGuid": "a67308b0-05bd-4d7a-8a34-70504aa81b35",
      "AdminUsername": "tschunk",
      "AdminFirstName": null,
      "AdminLastName": null,
      "UserFirstName": "IRIS Admin User",
      "UserLastName": "Allegion",
      "UserUsername": "IRISadminAllegion_alleg",
      "UserClientName": "Allegion MRC",
      "UserCompanyName": "TEST ORDER/DO NOT FULFILL - IRIS Strategic Marketing Support",
      "Url": "",
      "NumberOfHits": 10,
      "UpdateDate": "/Date(1634527177000)/"
    },
    {
      "Id": 44058,
      "AdminUserGuid": "a67308b0-05bd-4d7a-8a34-70504aa81b35",
      "AdminUsername": "tschunk",
      "AdminFirstName": null,
      "AdminLastName": null,
      "UserFirstName": "Iris",
      "UserLastName": "Admin",
      "UserUsername": "IRISadmin_srsdt",
      "UserClientName": "SRS Distribution",
      "UserCompanyName": "TEST COMPANY - DO NOT PROCESS",
      "Url": "",
      "NumberOfHits": 25,
      "UpdateDate": "/Date(1634007957000)/"
    }
  ]
}
