export const SidemenuList={
  getAdminSidebar:[
    {
      "text": "Main Navigation",
      "heading": true,
      "isAngular": false,
      "translate": null,
      "sref": null,
      "icon": null,
      "alert": null,
      "label": null,
      "srefChildren": null,
      "submenu": null
    },
    {
      "text": "Client",
      "heading": false,
      "isAngular": false,
      "translate": null,
      "sref": null,
      "icon": "fa fa-building",
      "alert": null,
      "label": null,
      "srefChildren": null,
      "submenu": [
        {
          "text": "List",
          "heading": false,
          "isAngular": true,
          "translate": null,
          "sref": "/Admin/#/Clients",
          "icon": null,
          "alert": null,
          "label": null,
          "srefChildren": null,
          "submenu": null
        },
        {
          "text": "Accounting/Funding",
          "heading": false,
          "isAngular": false,
          "translate": null,
          "sref": "/Admin/Accounting",
          "icon": null,
          "alert": null,
          "label": null,
          "srefChildren": null,
          "submenu": null
        },
        {
          "text": "Attributes",
          "heading": false,
          "isAngular": true,
          "translate": null,
          "sref": "/Admin/#/ClientAttribute",
          "icon": null,
          "alert": null,
          "label": null,
          "srefChildren": null,
          "submenu": null
        },
        {
          "text": "Categories",
          "heading": false,
          "isAngular": true,
          "translate": null,
          "sref": "/Admin/#/Category",
          "icon": null,
          "alert": null,
          "label": null,
          "srefChildren": null,
          "submenu": null
        },
        {
          "text": "Classifications",
          "heading": false,
          "isAngular": true,
          "translate": null,
          "sref": "/Admin/#/Classification",
          "icon": null,
          "alert": null,
          "label": null,
          "srefChildren": null,
          "submenu": null
        },
        {
          "text": "External Links",
          "heading": false,
          "isAngular": false,
          "translate": null,
          "sref": "/Admin/ExternalLinks",
          "icon": null,
          "alert": null,
          "label": null,
          "srefChildren": null,
          "submenu": null
        },
        {
          "text": "Forms",
          "heading": false,
          "isAngular": false,
          "translate": null,
          "sref": "/Admin/Form",
          "icon": null,
          "alert": null,
          "label": null,
          "srefChildren": null,
          "submenu": null
        },
        {
          "text": "Layouts",
          "heading": false,
          "isAngular": true,
          "translate": null,
          "sref": "/Admin/#/Client/Layout",
          "icon": null,
          "alert": null,
          "label": null,
          "srefChildren": null,
          "submenu": null
        },
        {
          "text": "Menus",
          "heading": false,
          "isAngular": false,
          "translate": null,
          "sref": "/Admin/Menu",
          "icon": null,
          "alert": null,
          "label": null,
          "srefChildren": null,
          "submenu": null
        },
        {
          "text": "Orders",
          "heading": false,
          "isAngular": true,
          "translate": null,
          "sref": "/Admin/#/Orders",
          "icon": null,
          "alert": null,
          "label": null,
          "srefChildren": [
            "/Admin/#/OrderLookup"
          ],
          "submenu": null
        },
        {
          "text": "Product Options",
          "heading": false,
          "isAngular": true,
          "translate": null,
          "sref": "/Admin/#/Client/ProductOption",
          "icon": null,
          "alert": null,
          "label": null,
          "srefChildren": null,
          "submenu": null
        },
        {
          "text": "Reimbursements",
          "heading": false,
          "isAngular": true,
          "translate": null,
          "sref": "/Admin/#/Reimbursement",
          "icon": null,
          "alert": null,
          "label": null,
          "srefChildren": null,
          "submenu": null
        },
        {
          "text": "Support",
          "heading": false,
          "isAngular": false,
          "translate": null,
          "sref": "/Admin/Support",
          "icon": null,
          "alert": null,
          "label": null,
          "srefChildren": null,
          "submenu": null
        },
        {
          "text": "Templates",
          "heading": false,
          "isAngular": true,
          "translate": null,
          "sref": "/Admin/#/Template",
          "icon": null,
          "alert": null,
          "label": null,
          "srefChildren": [
            "/Admin/#/EmailTemplate"
          ],
          "submenu": null
        },
        {
          "text": "Terms & Conditions",
          "heading": false,
          "isAngular": true,
          "translate": null,
          "sref": "/Admin/#/ClientTerms",
          "icon": null,
          "alert": null,
          "label": null,
          "srefChildren": null,
          "submenu": null
        },
        {
          "text": "Views",
          "heading": false,
          "isAngular": false,
          "translate": null,
          "sref": "/Admin/View",
          "icon": null,
          "alert": null,
          "label": null,
          "srefChildren": null,
          "submenu": null
        }
      ]
    },
    {
      "text": "Client Group",
      "heading": false,
      "isAngular": false,
      "translate": null,
      "sref": null,
      "icon": "fa fa-users",
      "alert": null,
      "label": null,
      "srefChildren": null,
      "submenu": [
        {
          "text": "List",
          "heading": false,
          "isAngular": true,
          "translate": null,
          "sref": "/Admin/#/ClientGroup",
          "icon": null,
          "alert": null,
          "label": null,
          "srefChildren": null,
          "submenu": null
        },
        {
          "text": "Attributes",
          "heading": false,
          "isAngular": true,
          "translate": null,
          "sref": "/Admin/#/ClientGroup/Attribute",
          "icon": null,
          "alert": null,
          "label": null,
          "srefChildren": null,
          "submenu": null
        },
        {
          "text": "Categories",
          "heading": false,
          "isAngular": true,
          "translate": null,
          "sref": "/Admin/#/ClientGroup/Category",
          "icon": null,
          "alert": null,
          "label": null,
          "srefChildren": null,
          "submenu": null
        },
        {
          "text": "Charges",
          "heading": false,
          "isAngular": false,
          "translate": null,
          "sref": "/Admin/ClientGroup/Charge",
          "icon": null,
          "alert": null,
          "label": null,
          "srefChildren": null,
          "submenu": null
        },
        {
          "text": "Client Ship Methods",
          "heading": false,
          "isAngular": false,
          "translate": null,
          "sref": "/Admin/#/ClientGroup/ClientShipMethod",
          "icon": null,
          "alert": null,
          "label": null,
          "srefChildren": null,
          "submenu": null
        },
        {
          "text": "Menus",
          "heading": false,
          "isAngular": false,
          "translate": null,
          "sref": "/Admin/#/ClientGroup/Menu",
          "icon": null,
          "alert": null,
          "label": null,
          "srefChildren": null,
          "submenu": null
        },
        {
          "text": "Preferred Vendors",
          "heading": false,
          "isAngular": false,
          "translate": null,
          "sref": "/Admin/#/ClientGroup/PreferredVendor",
          "icon": null,
          "alert": null,
          "label": null,
          "srefChildren": null,
          "submenu": null
        },
        {
          "text": "Products",
          "heading": false,
          "isAngular": true,
          "translate": null,
          "sref": "/Admin/#/ClientGroup/Product",
          "icon": null,
          "alert": null,
          "label": null,
          "srefChildren": null,
          "submenu": null
        },
        {
          "text": "Reports",
          "heading": false,
          "isAngular": false,
          "translate": null,
          "sref": "/Admin/#/ClientGroup/Report",
          "icon": null,
          "alert": null,
          "label": null,
          "srefChildren": null,
          "submenu": null
        },
        {
          "text": "Ship Methods",
          "heading": false,
          "isAngular": false,
          "translate": null,
          "sref": "/Admin/ClientGroup/ShipMethod",
          "icon": null,
          "alert": null,
          "label": null,
          "srefChildren": null,
          "submenu": null
        },
        {
          "text": "Users",
          "heading": false,
          "isAngular": true,
          "translate": null,
          "sref": "/Admin/#/ClientGroup/User",
          "icon": null,
          "alert": null,
          "label": null,
          "srefChildren": null,
          "submenu": null
        },
        {
          "text": "Widgets",
          "heading": false,
          "isAngular": false,
          "translate": null,
          "sref": "/Admin/ClientGroup/Widget",
          "icon": null,
          "alert": null,
          "label": null,
          "srefChildren": null,
          "submenu": null
        }
      ]
    },
    {
      "text": "Client User",
      "heading": false,
      "isAngular": false,
      "translate": null,
      "sref": null,
      "icon": "fa fa-user",
      "alert": null,
      "label": null,
      "srefChildren": null,
      "submenu": [
        {
          "text": "List",
          "heading": false,
          "isAngular": true,
          "translate": null,
          "sref": "/Admin/#/ClientUser",
          "icon": null,
          "alert": null,
          "label": null,
          "srefChildren": null,
          "submenu": null
        },
        {
          "text": "Addresses",
          "heading": false,
          "isAngular": true,
          "translate": null,
          "sref": "/Admin/#/Address",
          "icon": null,
          "alert": null,
          "label": null,
          "srefChildren": null,
          "submenu": null
        },
        {
          "text": "Attributes",
          "heading": false,
          "isAngular": true,
          "translate": null,
          "sref": "/Admin/#/ClientUserAttribute",
          "icon": null,
          "alert": null,
          "label": null,
          "srefChildren": null,
          "submenu": null
        },
        {
          "text": "Impersonate",
          "heading": false,
          "isAngular": true,
          "translate": null,
          "sref": "/Admin/#/Impersonate",
          "icon": null,
          "alert": null,
          "label": null,
          "srefChildren": null,
          "submenu": null
        }
      ]
    },
    {
      "text": "Product",
      "heading": false,
      "isAngular": false,
      "translate": null,
      "sref": null,
      "icon": "fa fa-gift",
      "alert": null,
      "label": null,
      "srefChildren": null,
      "submenu": [
        {
          "text": "List",
          "heading": false,
          "isAngular": true,
          "translate": null,
          "sref": "/Admin/#/Products",
          "icon": null,
          "alert": null,
          "label": null,
          "srefChildren": null,
          "submenu": null
        },
        {
          "text": "Attachment Types",
          "heading": false,
          "isAngular": true,
          "translate": null,
          "sref": "/Admin/#/AttachmentType",
          "icon": null,
          "alert": null,
          "label": null,
          "srefChildren": null,
          "submenu": null
        },
        {
          "text": "Attributes",
          "heading": false,
          "isAngular": true,
          "translate": null,
          "sref": "/Admin/#/Product/Attribute",
          "icon": null,
          "alert": null,
          "label": null,
          "srefChildren": null,
          "submenu": null
        },
        {
          "text": "Files",
          "heading": false,
          "isAngular": true,
          "translate": null,
          "sref": "/Admin/#/Product/File",
          "icon": null,
          "alert": null,
          "label": null,
          "srefChildren": null,
          "submenu": null
        },
        {
          "text": "Groups",
          "heading": false,
          "isAngular": true,
          "translate": null,
          "sref": "/Admin/#/Product/Group",
          "icon": null,
          "alert": null,
          "label": null,
          "srefChildren": null,
          "submenu": null
        },
        {
          "text": "Inventory",
          "heading": false,
          "isAngular": true,
          "translate": null,
          "sref": "/Admin/#/Inventory",
          "icon": null,
          "alert": null,
          "label": null,
          "srefChildren": null,
          "submenu": null
        },
        {
          "text": "Projects",
          "heading": false,
          "isAngular": true,
          "translate": null,
          "sref": "/Admin/#/Project",
          "icon": null,
          "alert": null,
          "label": null,
          "srefChildren": null,
          "submenu": null
        },
        {
          "text": "Promo Codes",
          "heading": false,
          "isAngular": true,
          "translate": null,
          "sref": "/Admin/#/PromoCode",
          "icon": null,
          "alert": null,
          "label": null,
          "srefChildren": null,
          "submenu": null
        }
      ]
    },
    {
      "text": "Resource",
      "heading": false,
      "isAngular": false,
      "translate": null,
      "sref": null,
      "icon": "fa fa-book",
      "alert": null,
      "label": null,
      "srefChildren": null,
      "submenu": [
        {
          "text": "Assets",
          "heading": false,
          "isAngular": true,
          "translate": null,
          "sref": "/Admin/#/AssetLibrary",
          "icon": null,
          "alert": null,
          "label": null,
          "srefChildren": null,
          "submenu": null
        },
        {
          "text": "Email",
          "heading": false,
          "isAngular": true,
          "translate": null,
          "sref": "/Admin/#/Email",
          "icon": null,
          "alert": null,
          "label": null,
          "srefChildren": null,
          "submenu": null
        },
        {
          "text": "News",
          "heading": false,
          "isAngular": true,
          "translate": null,
          "sref": "/Admin/#/Resources/News",
          "icon": null,
          "alert": null,
          "label": null,
          "srefChildren": null,
          "submenu": null
        },
        {
          "text": "Preferred Vendors",
          "heading": false,
          "isAngular": false,
          "translate": null,
          "sref": "/Admin/Resources/PreferredVendors",
          "icon": null,
          "alert": null,
          "label": null,
          "srefChildren": null,
          "submenu": null
        },
        {
          "text": "Queues",
          "heading": false,
          "isAngular": true,
          "translate": null,
          "sref": "/Admin/#/Resources/Queues",
          "icon": null,
          "alert": null,
          "label": null,
          "srefChildren": null,
          "submenu": null
        }
      ]
    },
    {
      "text": "Vendor",
      "heading": false,
      "isAngular": false,
      "translate": null,
      "sref": null,
      "icon": "fa fa-truck",
      "alert": null,
      "label": null,
      "srefChildren": null,
      "submenu": [
        {
          "text": "List",
          "heading": false,
          "isAngular": true,
          "translate": null,
          "sref": "/Admin/#/Vendor",
          "icon": null,
          "alert": null,
          "label": null,
          "srefChildren": null,
          "submenu": null
        },
        {
          "text": "Brands",
          "heading": false,
          "isAngular": true,
          "translate": null,
          "sref": "/Admin/#/Vendor/Brand",
          "icon": null,
          "alert": null,
          "label": null,
          "srefChildren": null,
          "submenu": null
        },
        {
          "text": "Handling",
          "heading": false,
          "isAngular": false,
          "translate": null,
          "sref": "/Admin/VendorHandling",
          "icon": null,
          "alert": null,
          "label": null,
          "srefChildren": null,
          "submenu": null
        },
        {
          "text": "Layouts",
          "heading": false,
          "isAngular": true,
          "translate": null,
          "sref": "/Admin/#/Vendor/Layout",
          "icon": null,
          "alert": null,
          "label": null,
          "srefChildren": null,
          "submenu": null
        },
        {
          "text": "Notices",
          "heading": false,
          "isAngular": false,
          "translate": null,
          "sref": "/Admin/VendorNotice",
          "icon": null,
          "alert": null,
          "label": null,
          "srefChildren": null,
          "submenu": null
        },
        {
          "text": "Product Options",
          "heading": false,
          "isAngular": true,
          "translate": null,
          "sref": "/Admin/#/Vendor/ProductOption",
          "icon": null,
          "alert": null,
          "label": null,
          "srefChildren": null,
          "submenu": null
        },
        {
          "text": "Reports",
          "heading": false,
          "isAngular": false,
          "translate": null,
          "sref": "/Admin/VendorReport",
          "icon": null,
          "alert": null,
          "label": null,
          "srefChildren": null,
          "submenu": null
        }
      ]
    },
    {
      "text": "System Navigation",
      "heading": true,
      "isAngular": false,
      "translate": null,
      "sref": null,
      "icon": null,
      "alert": null,
      "label": null,
      "srefChildren": null,
      "submenu": null
    },
    {
      "text": "Admin User",
      "heading": false,
      "isAngular": true,
      "translate": null,
      "sref": "/Admin/#/AdminUser",
      "icon": "fa fa-user",
      "alert": null,
      "label": null,
      "srefChildren": null,
      "submenu": null
    },
    {
      "text": "Currencies",
      "heading": false,
      "isAngular": true,
      "translate": null,
      "sref": "/Admin/#/Currency",
      "icon": "fa fa-dollar",
      "alert": null,
      "label": null,
      "srefChildren": null,
      "submenu": null
    },
    {
      "text": "Fonts",
      "heading": false,
      "isAngular": true,
      "translate": null,
      "sref": "/Admin/#/Fonts",
      "icon": "fa fa-font",
      "alert": null,
      "label": null,
      "srefChildren": null,
      "submenu": null
    },
    {
      "text": "Payment Gateways",
      "heading": false,
      "isAngular": false,
      "translate": null,
      "sref": null,
      "icon": "fa fa-credit-card",
      "alert": null,
      "label": null,
      "srefChildren": null,
      "submenu": [
        {
          "text": "Credit Card",
          "heading": false,
          "isAngular": false,
          "translate": null,
          "sref": "/Admin/CreditCardGateways",
          "icon": null,
          "alert": null,
          "label": null,
          "srefChildren": null,
          "submenu": null
        },
        {
          "text": "PayPal",
          "heading": false,
          "isAngular": false,
          "translate": null,
          "sref": "/Admin/PayPalGateways",
          "icon": null,
          "alert": null,
          "label": null,
          "srefChildren": null,
          "submenu": null
        }
      ]
    },
    {
      "text": "Reports",
      "heading": false,
      "isAngular": true,
      "translate": null,
      "sref": "/Admin/#/Reports",
      "icon": "fa fa-table",
      "alert": null,
      "label": null,
      "srefChildren": null,
      "submenu": null
    },
    {
      "text": "Ship Carriers",
      "heading": false,
      "isAngular": true,
      "translate": null,
      "sref": "/Admin/#/ShipCarrier",
      "icon": "fa fa-truck",
      "alert": null,
      "label": null,
      "srefChildren": null,
      "submenu": null
    },
    {
      "text": "Translation",
      "heading": false,
      "isAngular": false,
      "translate": null,
      "sref": null,
      "icon": "icon-globe",
      "alert": null,
      "label": null,
      "srefChildren": null,
      "submenu": [
        {
          "text": "Constants",
          "heading": false,
          "isAngular": true,
          "translate": null,
          "sref": "/Admin/#/Translation/Constant",
          "icon": null,
          "alert": null,
          "label": null,
          "srefChildren": null,
          "submenu": null
        },
        {
          "text": "Cultures",
          "heading": false,
          "isAngular": true,
          "translate": null,
          "sref": "/Admin/#/Translation/Culture",
          "icon": null,
          "alert": null,
          "label": null,
          "srefChildren": null,
          "submenu": null
        },
        {
          "text": "System Messages",
          "heading": false,
          "isAngular": true,
          "translate": null,
          "sref": "/Admin/#/Translation/Message",
          "icon": null,
          "alert": null,
          "label": null,
          "srefChildren": null,
          "submenu": null
        }
      ]
    },
    {
      "text": "Widgets",
      "heading": false,
      "isAngular": false,
      "translate": null,
      "sref": "/Admin/Widgets",
      "icon": "fa fa-table",
      "alert": null,
      "label": null,
      "srefChildren": null,
      "submenu": null
    }
  ]
}
