 export const vendorRootData={
$id: 1,
vendorId: 63,
vendorUserId: 2591,
vendorWebKey: "fa5864e3-33ee-4334-bbfa-0839397df0c0",
vendorUserNameDisplay: "tag_migrate",
isVendorUser: true,
isImpersonating: true,
actualUserNameDisplay: "tschunk",
gearBoxSignalRUrl: "https://localhost:44300/signalr",
applicationVersion: "1.0.8115.26925",
appEnvironment: "DEV",
isProduction: false,
appMode: "VENDOR",
selectedVendorId: "",
showVendorSelector: false,
fileUploadUrl: "/api/FileUpload",
viewLoading: false,
isEmbedded: false,
useSharedLayout: true,
pageTitle: "GearBox",
datePickerFormat: "MM/dd/yyyy",
viewport: "visible-lg",
headerModel: {
HasSupportPage: false,
HasClientUserListPage: false,
HasPromoCodePage: false,
CanInvoiceFreightSeparately: false,
Navbar:{
  Id: 0,
VendorId: 63,
Items:[{
  Id: 0,
  Name: "Home",
  ActiveInd: true,
  DisplayTxt: "Home",
  UseDisplayTextThroughoutPage: false,
  TypeId: 0,
  Description: "Home",
  PageUrl: "/Vendor/#/",
  OpenInNewWindowInd: false,
  OrderTitle: "",
  ShowInNavBar: true,
  IsActive: true,
},
{
  Id: 0,
  Name: "Inventory",
  ActiveInd: true,
  DisplayTxt: "Inventory",
  UseDisplayTextThroughoutPage: false,
  TypeId: 0,
  Description: "Inventory",
  PageUrl: "/Vendor/#/Inventory",
  OpenInNewWindowInd: false,
  OrderTitle: "Inventory",
  ShowInNavBar: true,
  IsActive: false
},
{
Id: 0,
Name: "Orders",
ActiveInd: true,
DisplayTxt: "Orders",
UseDisplayTextThroughoutPage: false,
TypeId: 0,
Description: "Orders",
PageUrl: "/Vendor/#/Orders",
OpenInNewWindowInd: false,
OrderTitle: "Orders",
ShowInNavBar: true,
IsActive: false,
},
{
  Id: 0,
  Name: "Ship Rates",
  ActiveInd: true,
  DisplayTxt: "Origin Addresses",
  UseDisplayTextThroughoutPage: false,
  TypeId: 0,
  Description: "Origin Addresses",
  PageUrl: "/Vendor/#/OriginAddress",
  OpenInNewWindowInd: false,
  OrderTitle: "Origin Addresses",
  ShowInNavBar: true,
  IsActive: false,
},
{
Id: 0,
Name: "Products",
ActiveInd: true,
DisplayTxt: "Products",
UseDisplayTextThroughoutPage: false,
TypeId: 0,
Description: "Products",
PageUrl: "/Vendor/#/Product",
OpenInNewWindowInd: false,
OrderTitle: "Products",
ShowInNavBar: true,
IsActive: false,
},
{
Id: 0,
Name: "Product Option Defaults",
ActiveInd: true,
DisplayTxt: "Product Option Defaults",
UseDisplayTextThroughoutPage: false,
TypeId: 0,
Description: "Product Option Defaults",
PageUrl: "/Vendor/#/ProductOption",
OpenInNewWindowInd: false,
OrderTitle: "Products Option Defaults",
ShowInNavBar: false,
IsActive: false
},
{
Id: 0,
Name: "Quotes",
ActiveInd: true,
DisplayTxt: "Quotes",
UseDisplayTextThroughoutPage: false,
TypeId: 0,
Description: "Quotes",
PageUrl: "/Vendor/#/Quotes",
OpenInNewWindowInd: false,
OrderTitle: "Quotes",
ShowInNavBar: true,
IsActive: false
},
{
  Id: 0,
  Name: "Reports",
  ActiveInd: true,
  DisplayTxt: "Reports",
  UseDisplayTextThroughoutPage: false,
  TypeId: 0,
  Description: "Reports",
  PageUrl: "/Vendor/#/Reports",
  OpenInNewWindowInd: false,
  OrderTitle: "Reports",
  ShowInNavBar: true,
  IsActive: false,
},
{
  Id: 0,
Name: "Ship Rates",
ActiveInd: true,
DisplayTxt: "Ship Rates",
UseDisplayTextThroughoutPage: false,
TypeId: 0,
Description: "Ship Rates",
PageUrl: "/Vendor/#/ShipRates",
OpenInNewWindowInd: false,
OrderTitle: "Ship Rates",
ShowInNavBar: true,
IsActive: false
},
{
  Id: 0,
  Name: "Shipping",
  ActiveInd: true,
  DisplayTxt: "Shipping",
  UseDisplayTextThroughoutPage: false,
  TypeId: 0,
  Description: "Shipping",
  PageUrl: "/Vendor/#/Shipping",
  OpenInNewWindowInd: false,
  OrderTitle: "Shipping",
  ShowInNavBar: true,
  IsActive: false
},
]
}
},
brandSettings: null,
notificationHubGroupName: "VendorUser2591",
isInitialized: true,
loadingMessage: null,
disableStickyNavBar: false,
userSettings:{
Culture: "en-US",
AvailableCultureCount: 0,
notificationHubGroupName: "VendorUser2591",
}
}
